/*
FastAPI

Testing AcceleratorTypeAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package perian

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/Perian-io/perian-go-client"
)

func Test_perian_AcceleratorTypeAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test AcceleratorTypeAPIService GetAcceleratorTypeById", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var acceleratorTypeId string

		resp, httpRes, err := apiClient.AcceleratorTypeAPI.GetAcceleratorTypeById(context.Background(), acceleratorTypeId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AcceleratorTypeAPIService GetAcceleratorTypeByRequirements", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.AcceleratorTypeAPI.GetAcceleratorTypeByRequirements(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AcceleratorTypeAPIService GetAllAcceleratorTypes", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.AcceleratorTypeAPI.GetAllAcceleratorTypes(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
