/*
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.2.8
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perian

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreditTopUpRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreditTopUpRequest{}

// CreditTopUpRequest JSON schema for credit topup request.
type CreditTopUpRequest struct {
	Amount Amount `json:"amount"`
}

type _CreditTopUpRequest CreditTopUpRequest

// NewCreditTopUpRequest instantiates a new CreditTopUpRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreditTopUpRequest(amount Amount) *CreditTopUpRequest {
	this := CreditTopUpRequest{}
	this.Amount = amount
	return &this
}

// NewCreditTopUpRequestWithDefaults instantiates a new CreditTopUpRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreditTopUpRequestWithDefaults() *CreditTopUpRequest {
	this := CreditTopUpRequest{}
	return &this
}

// GetAmount returns the Amount field value
func (o *CreditTopUpRequest) GetAmount() Amount {
	if o == nil {
		var ret Amount
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *CreditTopUpRequest) GetAmountOk() (*Amount, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *CreditTopUpRequest) SetAmount(v Amount) {
	o.Amount = v
}

func (o CreditTopUpRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreditTopUpRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["amount"] = o.Amount
	return toSerialize, nil
}

func (o *CreditTopUpRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"amount",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreditTopUpRequest := _CreditTopUpRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreditTopUpRequest)

	if err != nil {
		return err
	}

	*o = CreditTopUpRequest(varCreditTopUpRequest)

	return err
}

type NullableCreditTopUpRequest struct {
	value *CreditTopUpRequest
	isSet bool
}

func (v NullableCreditTopUpRequest) Get() *CreditTopUpRequest {
	return v.value
}

func (v *NullableCreditTopUpRequest) Set(val *CreditTopUpRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreditTopUpRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreditTopUpRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreditTopUpRequest(val *CreditTopUpRequest) *NullableCreditTopUpRequest {
	return &NullableCreditTopUpRequest{value: val, isSet: true}
}

func (v NullableCreditTopUpRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreditTopUpRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


