/*
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.2.8
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perian

import (
	"encoding/json"
)

// checks if the CpuQueryOutput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CpuQueryOutput{}

// CpuQueryOutput Query for the CPU attribute.
type CpuQueryOutput struct {
	Operator NullableOperator `json:"operator,omitempty"`
	Options NullableQueryOptions `json:"options,omitempty"`
	All *bool `json:"all,omitempty"`
	No NullableInt32 `json:"no,omitempty"`
	Cores NullableInt32 `json:"cores,omitempty"`
	Threads NullableInt32 `json:"threads,omitempty"`
	Speed NullableString `json:"speed,omitempty"`
}

// NewCpuQueryOutput instantiates a new CpuQueryOutput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCpuQueryOutput() *CpuQueryOutput {
	this := CpuQueryOutput{}
	var all bool = false
	this.All = &all
	return &this
}

// NewCpuQueryOutputWithDefaults instantiates a new CpuQueryOutput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCpuQueryOutputWithDefaults() *CpuQueryOutput {
	this := CpuQueryOutput{}
	var all bool = false
	this.All = &all
	return &this
}

// GetOperator returns the Operator field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CpuQueryOutput) GetOperator() Operator {
	if o == nil || IsNil(o.Operator.Get()) {
		var ret Operator
		return ret
	}
	return *o.Operator.Get()
}

// GetOperatorOk returns a tuple with the Operator field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CpuQueryOutput) GetOperatorOk() (*Operator, bool) {
	if o == nil {
		return nil, false
	}
	return o.Operator.Get(), o.Operator.IsSet()
}

// HasOperator returns a boolean if a field has been set.
func (o *CpuQueryOutput) HasOperator() bool {
	if o != nil && o.Operator.IsSet() {
		return true
	}

	return false
}

// SetOperator gets a reference to the given NullableOperator and assigns it to the Operator field.
func (o *CpuQueryOutput) SetOperator(v Operator) {
	o.Operator.Set(&v)
}
// SetOperatorNil sets the value for Operator to be an explicit nil
func (o *CpuQueryOutput) SetOperatorNil() {
	o.Operator.Set(nil)
}

// UnsetOperator ensures that no value is present for Operator, not even an explicit nil
func (o *CpuQueryOutput) UnsetOperator() {
	o.Operator.Unset()
}

// GetOptions returns the Options field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CpuQueryOutput) GetOptions() QueryOptions {
	if o == nil || IsNil(o.Options.Get()) {
		var ret QueryOptions
		return ret
	}
	return *o.Options.Get()
}

// GetOptionsOk returns a tuple with the Options field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CpuQueryOutput) GetOptionsOk() (*QueryOptions, bool) {
	if o == nil {
		return nil, false
	}
	return o.Options.Get(), o.Options.IsSet()
}

// HasOptions returns a boolean if a field has been set.
func (o *CpuQueryOutput) HasOptions() bool {
	if o != nil && o.Options.IsSet() {
		return true
	}

	return false
}

// SetOptions gets a reference to the given NullableQueryOptions and assigns it to the Options field.
func (o *CpuQueryOutput) SetOptions(v QueryOptions) {
	o.Options.Set(&v)
}
// SetOptionsNil sets the value for Options to be an explicit nil
func (o *CpuQueryOutput) SetOptionsNil() {
	o.Options.Set(nil)
}

// UnsetOptions ensures that no value is present for Options, not even an explicit nil
func (o *CpuQueryOutput) UnsetOptions() {
	o.Options.Unset()
}

// GetAll returns the All field value if set, zero value otherwise.
func (o *CpuQueryOutput) GetAll() bool {
	if o == nil || IsNil(o.All) {
		var ret bool
		return ret
	}
	return *o.All
}

// GetAllOk returns a tuple with the All field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CpuQueryOutput) GetAllOk() (*bool, bool) {
	if o == nil || IsNil(o.All) {
		return nil, false
	}
	return o.All, true
}

// HasAll returns a boolean if a field has been set.
func (o *CpuQueryOutput) HasAll() bool {
	if o != nil && !IsNil(o.All) {
		return true
	}

	return false
}

// SetAll gets a reference to the given bool and assigns it to the All field.
func (o *CpuQueryOutput) SetAll(v bool) {
	o.All = &v
}

// GetNo returns the No field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CpuQueryOutput) GetNo() int32 {
	if o == nil || IsNil(o.No.Get()) {
		var ret int32
		return ret
	}
	return *o.No.Get()
}

// GetNoOk returns a tuple with the No field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CpuQueryOutput) GetNoOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.No.Get(), o.No.IsSet()
}

// HasNo returns a boolean if a field has been set.
func (o *CpuQueryOutput) HasNo() bool {
	if o != nil && o.No.IsSet() {
		return true
	}

	return false
}

// SetNo gets a reference to the given NullableInt32 and assigns it to the No field.
func (o *CpuQueryOutput) SetNo(v int32) {
	o.No.Set(&v)
}
// SetNoNil sets the value for No to be an explicit nil
func (o *CpuQueryOutput) SetNoNil() {
	o.No.Set(nil)
}

// UnsetNo ensures that no value is present for No, not even an explicit nil
func (o *CpuQueryOutput) UnsetNo() {
	o.No.Unset()
}

// GetCores returns the Cores field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CpuQueryOutput) GetCores() int32 {
	if o == nil || IsNil(o.Cores.Get()) {
		var ret int32
		return ret
	}
	return *o.Cores.Get()
}

// GetCoresOk returns a tuple with the Cores field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CpuQueryOutput) GetCoresOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Cores.Get(), o.Cores.IsSet()
}

// HasCores returns a boolean if a field has been set.
func (o *CpuQueryOutput) HasCores() bool {
	if o != nil && o.Cores.IsSet() {
		return true
	}

	return false
}

// SetCores gets a reference to the given NullableInt32 and assigns it to the Cores field.
func (o *CpuQueryOutput) SetCores(v int32) {
	o.Cores.Set(&v)
}
// SetCoresNil sets the value for Cores to be an explicit nil
func (o *CpuQueryOutput) SetCoresNil() {
	o.Cores.Set(nil)
}

// UnsetCores ensures that no value is present for Cores, not even an explicit nil
func (o *CpuQueryOutput) UnsetCores() {
	o.Cores.Unset()
}

// GetThreads returns the Threads field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CpuQueryOutput) GetThreads() int32 {
	if o == nil || IsNil(o.Threads.Get()) {
		var ret int32
		return ret
	}
	return *o.Threads.Get()
}

// GetThreadsOk returns a tuple with the Threads field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CpuQueryOutput) GetThreadsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Threads.Get(), o.Threads.IsSet()
}

// HasThreads returns a boolean if a field has been set.
func (o *CpuQueryOutput) HasThreads() bool {
	if o != nil && o.Threads.IsSet() {
		return true
	}

	return false
}

// SetThreads gets a reference to the given NullableInt32 and assigns it to the Threads field.
func (o *CpuQueryOutput) SetThreads(v int32) {
	o.Threads.Set(&v)
}
// SetThreadsNil sets the value for Threads to be an explicit nil
func (o *CpuQueryOutput) SetThreadsNil() {
	o.Threads.Set(nil)
}

// UnsetThreads ensures that no value is present for Threads, not even an explicit nil
func (o *CpuQueryOutput) UnsetThreads() {
	o.Threads.Unset()
}

// GetSpeed returns the Speed field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CpuQueryOutput) GetSpeed() string {
	if o == nil || IsNil(o.Speed.Get()) {
		var ret string
		return ret
	}
	return *o.Speed.Get()
}

// GetSpeedOk returns a tuple with the Speed field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CpuQueryOutput) GetSpeedOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Speed.Get(), o.Speed.IsSet()
}

// HasSpeed returns a boolean if a field has been set.
func (o *CpuQueryOutput) HasSpeed() bool {
	if o != nil && o.Speed.IsSet() {
		return true
	}

	return false
}

// SetSpeed gets a reference to the given NullableString and assigns it to the Speed field.
func (o *CpuQueryOutput) SetSpeed(v string) {
	o.Speed.Set(&v)
}
// SetSpeedNil sets the value for Speed to be an explicit nil
func (o *CpuQueryOutput) SetSpeedNil() {
	o.Speed.Set(nil)
}

// UnsetSpeed ensures that no value is present for Speed, not even an explicit nil
func (o *CpuQueryOutput) UnsetSpeed() {
	o.Speed.Unset()
}

func (o CpuQueryOutput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CpuQueryOutput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Operator.IsSet() {
		toSerialize["operator"] = o.Operator.Get()
	}
	if o.Options.IsSet() {
		toSerialize["options"] = o.Options.Get()
	}
	if !IsNil(o.All) {
		toSerialize["all"] = o.All
	}
	if o.No.IsSet() {
		toSerialize["no"] = o.No.Get()
	}
	if o.Cores.IsSet() {
		toSerialize["cores"] = o.Cores.Get()
	}
	if o.Threads.IsSet() {
		toSerialize["threads"] = o.Threads.Get()
	}
	if o.Speed.IsSet() {
		toSerialize["speed"] = o.Speed.Get()
	}
	return toSerialize, nil
}

type NullableCpuQueryOutput struct {
	value *CpuQueryOutput
	isSet bool
}

func (v NullableCpuQueryOutput) Get() *CpuQueryOutput {
	return v.value
}

func (v *NullableCpuQueryOutput) Set(val *CpuQueryOutput) {
	v.value = val
	v.isSet = true
}

func (v NullableCpuQueryOutput) IsSet() bool {
	return v.isSet
}

func (v *NullableCpuQueryOutput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCpuQueryOutput(val *CpuQueryOutput) *NullableCpuQueryOutput {
	return &NullableCpuQueryOutput{value: val, isSet: true}
}

func (v NullableCpuQueryOutput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCpuQueryOutput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


