/*
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.2.8
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perian

import (
	"encoding/json"
	"fmt"
)

// checks if the CreditTopUpResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreditTopUpResponse{}

// CreditTopUpResponse JSON schema for credit topup endpoint.
type CreditTopUpResponse struct {
	Status *string `json:"status,omitempty"`
	Message *string `json:"message,omitempty"`
	Detail *string `json:"detail,omitempty"`
	StatusCode *int32 `json:"status_code,omitempty"`
	PaymentUrl string `json:"payment_url"`
	AdditionalProperties map[string]interface{}
}

type _CreditTopUpResponse CreditTopUpResponse

// NewCreditTopUpResponse instantiates a new CreditTopUpResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreditTopUpResponse(paymentUrl string) *CreditTopUpResponse {
	this := CreditTopUpResponse{}
	var status string = "Success"
	this.Status = &status
	var message string = "Operation was successful"
	this.Message = &message
	var detail string = ""
	this.Detail = &detail
	var statusCode int32 = 200
	this.StatusCode = &statusCode
	this.PaymentUrl = paymentUrl
	return &this
}

// NewCreditTopUpResponseWithDefaults instantiates a new CreditTopUpResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreditTopUpResponseWithDefaults() *CreditTopUpResponse {
	this := CreditTopUpResponse{}
	var status string = "Success"
	this.Status = &status
	var message string = "Operation was successful"
	this.Message = &message
	var detail string = ""
	this.Detail = &detail
	var statusCode int32 = 200
	this.StatusCode = &statusCode
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *CreditTopUpResponse) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreditTopUpResponse) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *CreditTopUpResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *CreditTopUpResponse) SetStatus(v string) {
	o.Status = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *CreditTopUpResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreditTopUpResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *CreditTopUpResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *CreditTopUpResponse) SetMessage(v string) {
	o.Message = &v
}

// GetDetail returns the Detail field value if set, zero value otherwise.
func (o *CreditTopUpResponse) GetDetail() string {
	if o == nil || IsNil(o.Detail) {
		var ret string
		return ret
	}
	return *o.Detail
}

// GetDetailOk returns a tuple with the Detail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreditTopUpResponse) GetDetailOk() (*string, bool) {
	if o == nil || IsNil(o.Detail) {
		return nil, false
	}
	return o.Detail, true
}

// HasDetail returns a boolean if a field has been set.
func (o *CreditTopUpResponse) HasDetail() bool {
	if o != nil && !IsNil(o.Detail) {
		return true
	}

	return false
}

// SetDetail gets a reference to the given string and assigns it to the Detail field.
func (o *CreditTopUpResponse) SetDetail(v string) {
	o.Detail = &v
}

// GetStatusCode returns the StatusCode field value if set, zero value otherwise.
func (o *CreditTopUpResponse) GetStatusCode() int32 {
	if o == nil || IsNil(o.StatusCode) {
		var ret int32
		return ret
	}
	return *o.StatusCode
}

// GetStatusCodeOk returns a tuple with the StatusCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreditTopUpResponse) GetStatusCodeOk() (*int32, bool) {
	if o == nil || IsNil(o.StatusCode) {
		return nil, false
	}
	return o.StatusCode, true
}

// HasStatusCode returns a boolean if a field has been set.
func (o *CreditTopUpResponse) HasStatusCode() bool {
	if o != nil && !IsNil(o.StatusCode) {
		return true
	}

	return false
}

// SetStatusCode gets a reference to the given int32 and assigns it to the StatusCode field.
func (o *CreditTopUpResponse) SetStatusCode(v int32) {
	o.StatusCode = &v
}

// GetPaymentUrl returns the PaymentUrl field value
func (o *CreditTopUpResponse) GetPaymentUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PaymentUrl
}

// GetPaymentUrlOk returns a tuple with the PaymentUrl field value
// and a boolean to check if the value has been set.
func (o *CreditTopUpResponse) GetPaymentUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PaymentUrl, true
}

// SetPaymentUrl sets field value
func (o *CreditTopUpResponse) SetPaymentUrl(v string) {
	o.PaymentUrl = v
}

func (o CreditTopUpResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreditTopUpResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Detail) {
		toSerialize["detail"] = o.Detail
	}
	if !IsNil(o.StatusCode) {
		toSerialize["status_code"] = o.StatusCode
	}
	toSerialize["payment_url"] = o.PaymentUrl

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreditTopUpResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"payment_url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreditTopUpResponse := _CreditTopUpResponse{}

	err = json.Unmarshal(data, &varCreditTopUpResponse)

	if err != nil {
		return err
	}

	*o = CreditTopUpResponse(varCreditTopUpResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "status")
		delete(additionalProperties, "message")
		delete(additionalProperties, "detail")
		delete(additionalProperties, "status_code")
		delete(additionalProperties, "payment_url")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreditTopUpResponse struct {
	value *CreditTopUpResponse
	isSet bool
}

func (v NullableCreditTopUpResponse) Get() *CreditTopUpResponse {
	return v.value
}

func (v *NullableCreditTopUpResponse) Set(val *CreditTopUpResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreditTopUpResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreditTopUpResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreditTopUpResponse(val *CreditTopUpResponse) *NullableCreditTopUpResponse {
	return &NullableCreditTopUpResponse{value: val, isSet: true}
}

func (v NullableCreditTopUpResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreditTopUpResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


