/*
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.2.8
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perian

import (
	"encoding/json"
	"fmt"
)

// AttributesHash struct for AttributesHash
type AttributesHash struct {
	string *string
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *AttributesHash) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	// try to unmarshal JSON data into string
	err = json.Unmarshal(data, &dst.string);
	if err == nil {
		jsonstring, _ := json.Marshal(dst.string)
		if string(jsonstring) == "{}" { // empty struct
			dst.string = nil
		} else {
			return nil // data stored in dst.string, return on the first match
		}
	} else {
		dst.string = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(AttributesHash)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *AttributesHash) MarshalJSON() ([]byte, error) {
	if src.string != nil {
		return json.Marshal(&src.string)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableAttributesHash struct {
	value *AttributesHash
	isSet bool
}

func (v NullableAttributesHash) Get() *AttributesHash {
	return v.value
}

func (v *NullableAttributesHash) Set(val *AttributesHash) {
	v.value = val
	v.isSet = true
}

func (v NullableAttributesHash) IsSet() bool {
	return v.isSet
}

func (v *NullableAttributesHash) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAttributesHash(val *AttributesHash) *NullableAttributesHash {
	return &NullableAttributesHash{value: val, isSet: true}
}

func (v NullableAttributesHash) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAttributesHash) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


