/*
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.2.8
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perian

import (
	"encoding/json"
)

// checks if the DockerRegistryCredentials type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DockerRegistryCredentials{}

// DockerRegistryCredentials DockerRegistryCredentials JSON schema for the docker_registry_credentials field in the          docker_run_parameters JSON field.
type DockerRegistryCredentials struct {
	Url *string `json:"url,omitempty"`
	Username *string `json:"username,omitempty"`
	Password *string `json:"password,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DockerRegistryCredentials DockerRegistryCredentials

// NewDockerRegistryCredentials instantiates a new DockerRegistryCredentials object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDockerRegistryCredentials() *DockerRegistryCredentials {
	this := DockerRegistryCredentials{}
	var url string = ""
	this.Url = &url
	var username string = ""
	this.Username = &username
	var password string = ""
	this.Password = &password
	return &this
}

// NewDockerRegistryCredentialsWithDefaults instantiates a new DockerRegistryCredentials object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDockerRegistryCredentialsWithDefaults() *DockerRegistryCredentials {
	this := DockerRegistryCredentials{}
	var url string = ""
	this.Url = &url
	var username string = ""
	this.Username = &username
	var password string = ""
	this.Password = &password
	return &this
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *DockerRegistryCredentials) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DockerRegistryCredentials) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *DockerRegistryCredentials) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *DockerRegistryCredentials) SetUrl(v string) {
	o.Url = &v
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *DockerRegistryCredentials) GetUsername() string {
	if o == nil || IsNil(o.Username) {
		var ret string
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DockerRegistryCredentials) GetUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.Username) {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *DockerRegistryCredentials) HasUsername() bool {
	if o != nil && !IsNil(o.Username) {
		return true
	}

	return false
}

// SetUsername gets a reference to the given string and assigns it to the Username field.
func (o *DockerRegistryCredentials) SetUsername(v string) {
	o.Username = &v
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *DockerRegistryCredentials) GetPassword() string {
	if o == nil || IsNil(o.Password) {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DockerRegistryCredentials) GetPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.Password) {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *DockerRegistryCredentials) HasPassword() bool {
	if o != nil && !IsNil(o.Password) {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *DockerRegistryCredentials) SetPassword(v string) {
	o.Password = &v
}

func (o DockerRegistryCredentials) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DockerRegistryCredentials) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.Username) {
		toSerialize["username"] = o.Username
	}
	if !IsNil(o.Password) {
		toSerialize["password"] = o.Password
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DockerRegistryCredentials) UnmarshalJSON(data []byte) (err error) {
	varDockerRegistryCredentials := _DockerRegistryCredentials{}

	err = json.Unmarshal(data, &varDockerRegistryCredentials)

	if err != nil {
		return err
	}

	*o = DockerRegistryCredentials(varDockerRegistryCredentials)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "url")
		delete(additionalProperties, "username")
		delete(additionalProperties, "password")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDockerRegistryCredentials struct {
	value *DockerRegistryCredentials
	isSet bool
}

func (v NullableDockerRegistryCredentials) Get() *DockerRegistryCredentials {
	return v.value
}

func (v *NullableDockerRegistryCredentials) Set(val *DockerRegistryCredentials) {
	v.value = val
	v.isSet = true
}

func (v NullableDockerRegistryCredentials) IsSet() bool {
	return v.isSet
}

func (v *NullableDockerRegistryCredentials) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDockerRegistryCredentials(val *DockerRegistryCredentials) *NullableDockerRegistryCredentials {
	return &NullableDockerRegistryCredentials{value: val, isSet: true}
}

func (v NullableDockerRegistryCredentials) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDockerRegistryCredentials) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


