/*
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.2.8
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perian

import (
	"encoding/json"
)

// checks if the GetOrganizationAuditLogsSuccess type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetOrganizationAuditLogsSuccess{}

// GetOrganizationAuditLogsSuccess Module for defining the GetOrganizationAuditLogsSuccess class.
type GetOrganizationAuditLogsSuccess struct {
	Status *string `json:"status,omitempty"`
	Message *string `json:"message,omitempty"`
	Detail *string `json:"detail,omitempty"`
	StatusCode *int32 `json:"status_code,omitempty"`
	AuditLogs []RequestLog `json:"audit_logs,omitempty"`
}

// NewGetOrganizationAuditLogsSuccess instantiates a new GetOrganizationAuditLogsSuccess object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetOrganizationAuditLogsSuccess() *GetOrganizationAuditLogsSuccess {
	this := GetOrganizationAuditLogsSuccess{}
	var status string = "Success"
	this.Status = &status
	var message string = "Operation was successful"
	this.Message = &message
	var detail string = ""
	this.Detail = &detail
	var statusCode int32 = 200
	this.StatusCode = &statusCode
	return &this
}

// NewGetOrganizationAuditLogsSuccessWithDefaults instantiates a new GetOrganizationAuditLogsSuccess object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetOrganizationAuditLogsSuccessWithDefaults() *GetOrganizationAuditLogsSuccess {
	this := GetOrganizationAuditLogsSuccess{}
	var status string = "Success"
	this.Status = &status
	var message string = "Operation was successful"
	this.Message = &message
	var detail string = ""
	this.Detail = &detail
	var statusCode int32 = 200
	this.StatusCode = &statusCode
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GetOrganizationAuditLogsSuccess) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrganizationAuditLogsSuccess) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GetOrganizationAuditLogsSuccess) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *GetOrganizationAuditLogsSuccess) SetStatus(v string) {
	o.Status = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *GetOrganizationAuditLogsSuccess) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrganizationAuditLogsSuccess) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *GetOrganizationAuditLogsSuccess) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *GetOrganizationAuditLogsSuccess) SetMessage(v string) {
	o.Message = &v
}

// GetDetail returns the Detail field value if set, zero value otherwise.
func (o *GetOrganizationAuditLogsSuccess) GetDetail() string {
	if o == nil || IsNil(o.Detail) {
		var ret string
		return ret
	}
	return *o.Detail
}

// GetDetailOk returns a tuple with the Detail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrganizationAuditLogsSuccess) GetDetailOk() (*string, bool) {
	if o == nil || IsNil(o.Detail) {
		return nil, false
	}
	return o.Detail, true
}

// HasDetail returns a boolean if a field has been set.
func (o *GetOrganizationAuditLogsSuccess) HasDetail() bool {
	if o != nil && !IsNil(o.Detail) {
		return true
	}

	return false
}

// SetDetail gets a reference to the given string and assigns it to the Detail field.
func (o *GetOrganizationAuditLogsSuccess) SetDetail(v string) {
	o.Detail = &v
}

// GetStatusCode returns the StatusCode field value if set, zero value otherwise.
func (o *GetOrganizationAuditLogsSuccess) GetStatusCode() int32 {
	if o == nil || IsNil(o.StatusCode) {
		var ret int32
		return ret
	}
	return *o.StatusCode
}

// GetStatusCodeOk returns a tuple with the StatusCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrganizationAuditLogsSuccess) GetStatusCodeOk() (*int32, bool) {
	if o == nil || IsNil(o.StatusCode) {
		return nil, false
	}
	return o.StatusCode, true
}

// HasStatusCode returns a boolean if a field has been set.
func (o *GetOrganizationAuditLogsSuccess) HasStatusCode() bool {
	if o != nil && !IsNil(o.StatusCode) {
		return true
	}

	return false
}

// SetStatusCode gets a reference to the given int32 and assigns it to the StatusCode field.
func (o *GetOrganizationAuditLogsSuccess) SetStatusCode(v int32) {
	o.StatusCode = &v
}

// GetAuditLogs returns the AuditLogs field value if set, zero value otherwise.
func (o *GetOrganizationAuditLogsSuccess) GetAuditLogs() []RequestLog {
	if o == nil || IsNil(o.AuditLogs) {
		var ret []RequestLog
		return ret
	}
	return o.AuditLogs
}

// GetAuditLogsOk returns a tuple with the AuditLogs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrganizationAuditLogsSuccess) GetAuditLogsOk() ([]RequestLog, bool) {
	if o == nil || IsNil(o.AuditLogs) {
		return nil, false
	}
	return o.AuditLogs, true
}

// HasAuditLogs returns a boolean if a field has been set.
func (o *GetOrganizationAuditLogsSuccess) HasAuditLogs() bool {
	if o != nil && !IsNil(o.AuditLogs) {
		return true
	}

	return false
}

// SetAuditLogs gets a reference to the given []RequestLog and assigns it to the AuditLogs field.
func (o *GetOrganizationAuditLogsSuccess) SetAuditLogs(v []RequestLog) {
	o.AuditLogs = v
}

func (o GetOrganizationAuditLogsSuccess) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetOrganizationAuditLogsSuccess) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Detail) {
		toSerialize["detail"] = o.Detail
	}
	if !IsNil(o.StatusCode) {
		toSerialize["status_code"] = o.StatusCode
	}
	if !IsNil(o.AuditLogs) {
		toSerialize["audit_logs"] = o.AuditLogs
	}
	return toSerialize, nil
}

type NullableGetOrganizationAuditLogsSuccess struct {
	value *GetOrganizationAuditLogsSuccess
	isSet bool
}

func (v NullableGetOrganizationAuditLogsSuccess) Get() *GetOrganizationAuditLogsSuccess {
	return v.value
}

func (v *NullableGetOrganizationAuditLogsSuccess) Set(val *GetOrganizationAuditLogsSuccess) {
	v.value = val
	v.isSet = true
}

func (v NullableGetOrganizationAuditLogsSuccess) IsSet() bool {
	return v.isSet
}

func (v *NullableGetOrganizationAuditLogsSuccess) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetOrganizationAuditLogsSuccess(val *GetOrganizationAuditLogsSuccess) *NullableGetOrganizationAuditLogsSuccess {
	return &NullableGetOrganizationAuditLogsSuccess{value: val, isSet: true}
}

func (v NullableGetOrganizationAuditLogsSuccess) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetOrganizationAuditLogsSuccess) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


